### ISSUE TITLE
cli.py is broken

### ISSUE THREAD

**Issue by tomstom** [ElvinC/gyroflow#139]
I get the following error, when I try to run the stabilisation by command line:

```
E:\Benutzer\Tom\Dokumente\Programme\GyroFlow30Dev>poetry run python cli.py C:\Users\Tom\Desktop\C0711.MP4 --camera "C:\Users\Tom\Desktop\ZV1 myStuff\Sony_ZV1_4k30.json" --gyro C:\Users\Tom\Desktop\C0711_gyro.bbl.csv --sync 5 --smooth 0.5 --resolution 4k --bitrate 100 --vcodec h264_nvenc --out C:\Users\Tom\Desktop\C0711_cli.MP4
C:\Users\Tom\Desktop\C0711.MP4 C:\Users\Tom\Desktop\C0711_cli.MP4 0.5 5
C:\Users\Tom\Desktop\C0711_gyro.bbl.csv has log C:\Users\Tom\Desktop\C0711_gyro.bbl.csv with type 'Blackbox CSV file'
Preset name: Sony ZV1 4k30
Note: max zoomed out
Made with 17 frames using calibrator version 0.3.0-beta on date 2021-12-30
Note: Versions don't match. Calibrator: 0.3.0-beta-dev, Preset: 0.3.0-beta. Should be fine though.
C:\Users\Tom\Desktop\C0711_gyro.bbl.csv
Blackbox CSV file
Blackbox CSV file
average_frame_duration: 0.000496670958201485
missing_runs: []
Appending 0.000498..=48.029573
average_frame_duration: 0.000496670958201485
missing_runs: []
Appending 0.000498..=48.029573
1
Starting parallel auto sync
C:\Users\Tom\Desktop\C0711.MP4 C:\Users\Tom\Desktop\C0711_cli.MP4 0.5 5
C:\Users\Tom\Desktop\C0711_gyro.bbl.csv has log C:\Users\Tom\Desktop\C0711_gyro.bbl.csv with type 'Blackbox CSV file'
Preset name: Sony ZV1 4k30
Note: max zoomed out
Made with 17 frames using calibrator version 0.3.0-beta on date 2021-12-30
Note: Versions don't match. Calibrator: 0.3.0-beta-dev, Preset: 0.3.0-beta. Should be fine though.
C:\Users\Tom\Desktop\C0711_gyro.bbl.csv
Blackbox CSV file
Blackbox CSV file
average_frame_duration: 0.000496670958201485
missing_runs: []
Appending 0.000498..=48.029573
average_frame_duration: 0.000496670958201485
missing_runs: []
Appending 0.000498..=48.029573
1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Benutzer\Tom\Dokumente\Programme\GyroFlow30Dev\cli.py", line 122, in <module>
    success = stab.full_auto_sync_parallel(
  File "E:\Benutzer\Tom\Dokumente\Programme\GyroFlow30Dev\stabilizer.py", line 672, in full_auto_sync_parallel
    sync_results = ps.begin_sync_parallel()
  File "E:\Benutzer\Tom\Dokumente\Programme\GyroFlow30Dev\stabilizer.py", line 2627, in begin_sync_parallel
    pool = mp.Pool(n_proc)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
C:\Users\Tom\Desktop\C0711.MP4 C:\Users\Tom\Desktop\C0711_cli.MP4 0.5 5
C:\Users\Tom\Desktop\C0711_gyro.bbl.csv has log C:\Users\Tom\Desktop\C0711_gyro.bbl.csv with type 'Blackbox CSV file'
Preset name: Sony ZV1 4k30
Note: max zoomed out
**....This is a never ending loop...**
```

**Comment by SpoddyCoder** [comment]
Duplicate of this open issue - could you add your report to it as a comment, thanks!....

https://github.com/ElvinC/gyroflow/issues/113

(grouping them together will increase traction)
