### ISSUE TITLE
RuntimeError: No predictor found for 10

### ISSUE THREAD

**Issue by codegrue** [ElvinC/gyroflow#59]
I get this error when I try to "Apply Settings and compute sync". 

Log info:

```
10.0 degree uptilt
using raw blackbox file
Preset name: Caddx_Vista__16by9 DVR
Note:
Made with 10 frames using calibrator version 0.2.0-alpha on date 2021-02-06
Warning: Versions don't match. Calibrator: 0.2.1-alpha, Preset: 0.2.0-alpha
F:/OneDrive/Hobbies/Drones/Videos/2021-06-17 Aggressive with Flywoo/btfl_all.bbl
Opening F:/OneDrive/Hobbies/Drones/Videos/2021-06-17 Aggressive with Flywoo/btfl_all.bbl
Traceback (most recent call last):
  File "gyroflow.py", line 2026, in recompute_stab
  File "stabilizer.py", line 1035, in __init__
  File "blackbox_extract.py", line 9, in __init__
  File "orangebox\parser.py", line 91, in load
  File "orangebox\reader.py", line 75, in __init__
  File "orangebox\reader.py", line 142, in set_log_index
  File "orangebox\reader.py", line 213, in _build_field_defs
RuntimeError: No predictor found for 10
```

**Comment by ElvinC** [comment]
Convert the blackbox log to a CSV using the blackbox explorer and use that instead.
