### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by minzukas** [ElvinC/gyroflow#78]
Any suggestions how to get it working? I am on ubnutu, 20.04.3 LTS  and get this one:

mindaugas@tux:~/Downloads/gyroflow-master$ poetry run python3 gyroflow.py
Traceback (most recent call last):
  File "gyroflow.py", line 11, in <module>
    import calibrate_video
  File "/home/mindaugas/.cache/pypoetry/virtualenvs/gyroflow-iray_dlu-py3.8/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/mindaugas/Downloads/gyroflow-master/calibrate_video.py", line 6, in <module>
    from tkinter import Tk
  File "/home/mindaugas/.cache/pypoetry/virtualenvs/gyroflow-iray_dlu-py3.8/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tkinter'

**Comment by ElvinC** [comment]
`sudo apt-get install python3-tk` or equivalent should do it
