### ISSUE TITLE
Unable to open gyro data from Insta360 SMO 4k

### ISSUE THREAD

**Issue by DarthPlasma** [ElvinC/gyroflow#86]
I tried to open gyro data in the mp4 metadata but gyroflow gave me an error message:

```
Traceback (most recent call last):
  File "gyroflow.py", line 2371, in input_gyro_plot
  File "gyrolog.py", line 306, in extract_log
  File "gyrolog.py", line 876, in extract_log_internal
  File "insta360_utility.py", line 11, in get_insta360_gyro_data
  File "insta360_utility.py", line 46, in _extract_metadata
OSError: [Errno 22] Invalid argument
```

Is currently smo 4k unsupported in gyroflow?

**Comment by DarthPlasma** [comment]
After messing around, i realized that the file was corrupt. Trying with different SD card seem to have solved the problem. Closing this issue. Thank you
