### ISSUE TITLE
Hero 7 "Failed to Extract GPMF Gyro / Motion Data" + Many other ERRORS 

### ISSUE THREAD

**Issue by bigjoncoop** [ElvinC/gyroflow#88]
Using my GOPRO HERO 7 and trying to open any saved MP4 file on the SDCard, GYROFLOW outputs the following errors.

(When using: goprotelemetryextractor.com it does indeed extract and show gyro/accel data etc...)
***GOPRO HERO 7 FIRMWARE VERSON: 01.90.71
***GyroFlow Verson:  gyroflow-0.3.0-beta-win64

_*After Opening GoPro Hero 7 MP4 File*_

[warn] [/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[2]/minf/atom[2]/stbl/atom[0]/stsd/sample_entry[0]/atom[0]/esds/ES/decConfigDescr/reserved] padding contents doesn't look normal (invalid pattern)
[warn] [/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
Couldn't guess log type of C:/Users/Administrator/Downloads/george1.MP4

_*After Selecting "Attempt Auto Snyc" *_

0.0 degree gyro/camera angle
Preset name: GoPro_Hero 7 Black__4K 60 wide 16by9 1/120
Note: ND16
Made with 28 frames using calibrator version 0.2.1-alpha on date 2021-02-09
Note: Versions don't match. Calibrator: 0.3.0-beta, Preset: 0.2.1-alpha. Should be fine though.
C:/Users/Administrator/Downloads/george1.MP4
[warn] [/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[2]/minf/atom[2]/stbl/atom[0]/stsd/sample_entry[0]/atom[0]/esds/ES/decConfigDescr/reserved] padding contents doesn't look normal (invalid pattern)
[warn] [/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
'STRM'
Failed to extract GPMF gyro
Failed to extract and parse motion data
Analyzing 9 slices
Analyzing frame: 100%|█████████████████████████████████████████████████████████████████| 30/30 [00:07<00:00,  4.07it/s]
Traceback (most recent call last):
  File "gyroflow.py", line 2548, in auto_sync_start
  File "stabilizer.py", line 610, in full_auto_sync
  File "stabilizer.py", line 383, in multi_sync_add_slice
  File "stabilizer.py", line 844, in optical_flow_comparison
  File "stabilizer.py", line 951, in estimate_gyro_offset
AttributeError: 'NoneType' object has no attribute 'get_raw_data'

**Comment by ElvinC** [comment]
This issue has been reported for some hero 7 users, will look more into it.
